---

- name: delete all swap entries
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
  register: lineinfile_result

- name: disable swap
  command: /sbin/swapoff -a
  when: lineinfile_result.changed
