---

- name: Set Consul version
  set_fact:
    ConsulVersion: 1.4.0

# https://learn.hashicorp.com/consul/getting-started/install
- name: Download and Unarchive Consul binary zip file. 
  unarchive:
    src: https://releases.hashicorp.com/consul/{{ ConsulVersion }}/consul_{{ ConsulVersion }}_linux_amd64.zip
    dest: /usr/local/bin
    owner: root
    group: root
    remote_src: yes
    mode: 0555
  register: consul_binary_install_result

# https://learn.hashicorp.com/consul/advanced/day-1-operations/deployment-guide#install-consul
- name: enable Consul automcompletion
  shell: "{{ item }}"
  when: consul_binary_install_result.changed
  loop:
    - /usr/local/bin/consul -autocomplete-install
    - complete -C /usr/local/bin/consul consul

- name: Create the 'consul' user service account 
  user:
    name: consul
    comment: consul service account
    system: true
    shell: /bin/false
    home: /etc/consul.d
    create_home: false

- name: Create directories used by Consul 
  file:
    path: "{{ item }}" 
    state: directory
    mode: 0750
    owner: consul
    group: consul
  loop:
    - /etc/consul.d
    - /opt/consul