---

- name: Get kube join command
  shell: /bin/grep 'kubeadm join' /vagrant/kube_cache/kubeadm_init_output.txt | /bin/sed 's/^[[:space:]]*//'
  register: join_command_output


- name: debug
  debug:
    msg: "{{ join_command_output }}"