---

- name: Get kube join command
  shell: /usr/bin/tail -2 /vagrant/kube_cache/kubeadm_init_output.txt 
  register: join_command_output


- name: run kubeadm join command
  command: "{{ join_command_output.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  