---

- name: Create folders for calico
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /root/kubernetes
    - /root/kubernetes/calico


# https://docs.projectcalico.org/v3.6/getting-started/kubernetes/
- name: Download calico files
  get_url:
    url: "{{ item }}"
    dest: "/root/kubernetes/calico/{{ item | basename }}"
    mode: 0440
  loop:
    - https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
    - https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
 # the calico.yaml file specifies the default pod cidr. You can update this if you like. This is also the value 
 # that needs to be fed into the kubeadm init command.



- name: Run kubeadm init command
  command: /usr/bin/kubeadm init --pod-network-cidr=192.168.0.0/16
#  args:
#    creates:
  register: kubeadm_init_output


- name: kubeadm init output
  copy:
    content: "{{ kubeadm_init_output }}"
    dest: /root/kubernetes/kubeadm_init_output.txt