---
- hosts: all
  become: yes 
  gather_facts: yes 
  roles:
    - { role: common-packages, tags: common-packages }
    - { role: consul, tags: consul }
    - { role: consul-templates, tags: consul-templates }