---

- name: Set Consul Template version
  set_fact:
    ConsulTemplateVersion: 0.19.5

# https://learn.hashicorp.com/consul/getting-started/install
- name: Download and Unarchive Consul Tempalate binary zip file. 
  unarchive:
    src: https://releases.hashicorp.com/consul-template/{{ ConsulTemplateVersion }}/consul-template_{{ ConsulTemplateVersion }}_linux_amd64.zip
    dest: /usr/local/bin
    owner: root
    group: root
    remote_src: yes
    mode: 0555
  register: consul_template_binary_install_result

# https://learn.hashicorp.com/consul/advanced/day-1-operations/deployment-guide#install-consul
#- name: enable Consul automcompletion
#  shell: "{{ item }}"
#  when: consul_template_binary_install_result.changed
#  loop:
#    - /usr/local/bin/consul -autocomplete-install
#    - complete -C /usr/local/bin/consul consul


#- name: Create the 'consul-template' user service account 
#  user:
#    name: consul-template
#    comment: consul template service account
#    system: true
#    shell: /bin/bash
#    home: /etc/consul-template
#    create_home: false

- name: Create directories used by Consul template
  file:
    path: "{{ item }}" 
    state: directory
    mode: 0750
    owner: root
    group: root
  loop:
    - /etc/consul-template
#    - /etc/consul-template/consul-template.d
    - /etc/consul-template/configs
    - /opt/consul-template


