---

# https://learn.hashicorp.com/consul/advanced/day-1-operations/deployment-guide
- name: deploy consul daemon - which is used by both consul agents and servers
  copy: 
    src: consul-template.service
    dest: /etc/systemd/system/consul-template.service
    owner: root 
    group: root 
    mode: 0640
  notify: restart consul-template

- name: Make sure consul service is running
  systemd:
    state: started
    enabled: true
    name: consul-template
    daemon_reload: yes