- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
 
    - name: Load in users.yml data
      include_vars: "/etc/consul-template/ansible/rendered-templates/group_vars/common/users.yml"
 
    - name: Setup users
      user:
        name: "{{ item.name }}" 
        comment: "{{ item.comment }}"
#        groups: "{{ item.groups }}" 
        remove: no
        shell: /bin/bash
        state: "{{ item.state }}" 
      loop: "{{ users }}"
 
    - name: Setup public keys 
      authorized_key: 
        user: "{{ item.name }}"
        state: "{{ item.state }}"
        key: "{{ item.pubkey }}"
      loop: "{{ users }}"
